Repository ebi-gene-expression-group/atlas-web-single-cell, pull requests merged in 2023-11, with the labels that each got.

#353 Refactor cell types endpoint
  app/src/main/java/uk/ac/ebi/atlas/search/JsonGeneSearchController.java
  app/src/main/java/uk/ac/ebi/atlas/search/celltype/CellTypeSearchDao.java
  app/src/main/java/uk/ac/ebi/atlas/search/celltype/CellTypeSearchService.java
  app/src/main/java/uk/ac/ebi/atlas/search/organismpart/OrganismPartSearchDao.java
  app/src/main/java/uk/ac/ebi/atlas/solr/SingleCellSolrUtils.java
  app/src/test/java/uk/ac/ebi/atlas/search/JsonGeneSearchControllerIT.java
  app/src/test/java/uk/ac/ebi/atlas/search/JsonGeneSearchControllerWIT.java
  app/src/test/java/uk/ac/ebi/atlas/search/celltype/CellTypeSearchDaoIT.java
  app/src/test/java/uk/ac/ebi/atlas/search/celltype/CellTypeSearchServiceTest.java
Labels: gene search

#370 Replace lodash function with JS function
  app/src/main/javascript/bundles/experiment-page/src/TSnePlotViewRoute.js
Labels: bug

#366 [Chore] Add experiment design loading to our local env
  docker/prepare-dev-environment/postgres/docker-compose.yml
  docker/prepare-dev-environment/solr/Dockerfile
Labels: feature
