Repository ebi-gene-expression-group/atlas-web-single-cell, pull requests merged in 2024-08, with the labels that each got.

#446 Bugfix search button not working after an initial metadata search
  app/src/main/javascript/bundles/gene-search/html/index.html
  app/src/main/javascript/bundles/gene-search/src/GeneSearch.js
Labels: cell type wheel

#449 [Chore] Get expression unit from the DB for Cell plots tab / Gene Expression part
  app/src/main/java/uk/ac/ebi/atlas/experimentpage/cellplot/CellPlotDao.java
  app/src/main/java/uk/ac/ebi/atlas/experimentpage/cellplot/CellPlotJsonSerializer.java
  app/src/main/java/uk/ac/ebi/atlas/experimentpage/cellplot/CellPlotService.java
  app/src/test/java/uk/ac/ebi/atlas/experimentpage/cellplot/CellPlotDaoIT.java
  app/src/test/java/uk/ac/ebi/atlas/experimentpage/cellplot/CellPlotServiceTest.java
  app/src/test/resources/fixtures/experiment.sql
Labels: enhancement

#448 Bugfix/species filter is getting ignored in the metadata search
  README.md
  app/src/main/javascript/bundles/cell-type-wheel-heatmap/package.json
  app/src/main/javascript/bundles/experiment-page/package.json
  app/src/main/javascript/bundles/experiment-table/package.json
  app/src/main/javascript/bundles/gene-search/package.json
  app/src/main/javascript/package.json
Labels: bug

#450 Experiment unit from db for marker genes
  app/src/main/java/uk/ac/ebi/atlas/experimentpage/markergenes/HighchartsHeatmapAdapter.java
  app/src/main/java/uk/ac/ebi/atlas/experimentpage/markergenes/MarkerGene.java
  app/src/main/java/uk/ac/ebi/atlas/experimentpage/markergenes/MarkerGenesDao.java
  app/src/main/java/uk/ac/ebi/atlas/search/metadata/MultiexperimentCellTypeMarkerGenesDao.java
  app/src/test/java/uk/ac/ebi/atlas/experimentpage/markergenes/HighchartsHeatmapAdapterTest.java
  app/src/test/java/uk/ac/ebi/atlas/experimentpage/markergenes/MarkerGeneServiceTest.java
Labels: enhancement
